############################################################
# +------------------------------------------------------+ #
# |                       PrettySigns                    | #
# +------------------------------------------------------+ #
############################################################

#Config version - 0.1
#Developed by Kenny Williams | exload
#Website: http://mcacraft.com/
#Forums: http://forums.mcacraft.com/
#YouTube: http://www.youtube.com/mrcomputeranswers
#Questions, comments, or bugs, email me: support@mcacraft.com

#Mcstats.org reporting. This information is harmless and simply provides me, the
#developer, with useful stats on this plugin.
mcstats: true

#All updates are effective after a restart. By default this is set to false. When set
#to false the plugin will prompt you to do the command /ps update to fetch the latest build
#from BukkitDev. If set to true, the plugin will not warn you and will download the update
#automatically.
auto-update: false

#Do NOT mess with this. It WILL break the plugin.
config-version: 0.1
